O_ScavProtoType.UI/Controllers/HuntsController.cs
using System;
using System.Collections.Generic;

using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using O_ScavProtoType.DAL;
using O_ScavProtoType.Model;
using System.Diagnostics;
using O_ScavProtoType.UI.Models;
using Microsoft.AspNet.Identity;

namespace O_ScavProtoType.UI.Controllers
{
    //[RequireHttps]
    [Authorize(Roles = "Administrator, Builder")]
    public class HuntsController : Controller
    {
        private HuntRepo Repo = new HuntRepo();

        public ActionResult Index()
        {
            string builderId = User.Identity.GetUserId();
            List<Hunt> hunts = Repo.GetUserHunts(builderId);

            return View(hunts);
        }

        [Authorize]
        public ActionResult Manage()
        {
            return View();
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Hunt hunt = Repo.GetHunt(id);

            if (hunt == null)
            {
                return HttpNotFound();
            }

            return View(hunt);
        }

        [Authorize(Roles = "Administrator, Builder")]
        public ActionResult Create()
        {
            var huntvm = new HuntVM();
            return View(huntvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HuntVM huntVm)
        {
            var hunt = new Hunt();
            hunt.Name = huntVm.Hunt.Name;
            hunt.POIs = new List<POI>();
            hunt.POIs.Add(huntVm.NewPoi);

            string userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                Repo.CreateHunt(hunt, userId);
            }

            return View("Index");
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Hunt hunt = Repo.GetHunt(id);

            if (hunt == null)
            {
                return HttpNotFound();
            }

            var huntVm = new HuntVM();
            huntVm.Hunt = hunt;
            huntVm.pois = hunt.POIs;

            return View(huntVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HuntVM huntVm)
        {
            //hunt name and 1 poi can change
            Hunt huntToUpdate = Repo.GetHunt(huntVm.Hunt.Id);
            huntToUpdate.Name = huntVm.Hunt.Name;

            if(huntToUpdate.POIs == null)
            {
                huntToUpdate.POIs = new List<POI>() { huntVm.NewPoi };
            }
            else
            {
                huntToUpdate.POIs.Add(huntVm.NewPoi);
            }
            
            if (ModelState.IsValid)
            {
                Repo.UpdateHunt(huntToUpdate);

                return RedirectToAction("edit", new { id = huntToUpdate.Id });
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditPOI(int? poiID)
        {
            if (poiID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var hunts = Repo.GetAllHunts();

            POI poi = hunts
                .SelectMany(h => h.POIs
                .Where(p => p.Id == poiID))
                .SingleOrDefault();

            var PoiVM = new PoiVM();

            PoiVM.Poi = poi;
            PoiVM.Task = poi.Task;

            return View("poi", PoiVM);

        }

        [HttpPost]
        public ActionResult EditPOI(PoiVM poiVm, HttpPostedFileBase upload)
        {
            int huntID = poiVm.Poi.HuntID;
            Hunt huntToUpdate = Repo.GetHunt(huntID);
            POI poi = huntToUpdate.POIs
                .Where(p => p.Id == poiVm.Poi.Id)
                .Single();

            if (ModelState.IsValid)
            {
                huntToUpdate.POIs.Remove(poi);

                if (upload != null && upload.ContentLength > 0)
                {
                    var image = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.PoiImage,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        image.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    //create or replace the file
                    poi.Files = new List<File> { image };
                }

                poi.Name = poiVm.Poi.Name;
                poi.Description = poiVm.Poi.Description;

                
                huntToUpdate.POIs.Add(poi);

                Repo.UpdateHunt(huntToUpdate);

                return RedirectToAction("EditPOI", new { poiID = poi.Id });
            }

            ViewBag.Message = "Item Not Edited";
            return RedirectToAction("Index");
        }

        public ActionResult CreateTasks(PoiVM poiVM)
        {
            var task = poiVM.NewTask;
            if (poiVM.taskType == TaskTypeNum.Quiz)
            {
                var quizVM = new QuizVM();
                quizVM.QuizAnswers = new QuizAnswers();
                quizVM.QuizAnswers.AnswerA = "";
                quizVM.QuizAnswers.AnswerB = "";
                quizVM.QuizAnswers.AnswerC = "";
                quizVM.QuizAnswers.AnswerD = "";
                quizVM.TaskText = task.TaskText;
                quizVM.poiID = poiVM.Poi.Id;
                return View("CreateQuiz", quizVM);
            }

            if (poiVM.taskType == TaskTypeNum.Image)
            {
                var imageVM = new ImageVM();
                imageVM.TaskText = task.TaskText;
                var image = new ImageTask();
                image.Files = new List<File>();
                imageVM.Image = image;
                imageVM.poiID = poiVM.Poi.Id;
                return View("CreateImage", imageVM);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult CreateQuizTask(QuizVM quizVM)
        {
            //initalize taskType and Task Objects
            var task = new Task();

            if (ModelState.IsValid)
            {
                var quiz = new QuizTask();
                quiz.TaskType = new TaskType();
                quiz.QuizAnswers = quizVM.QuizAnswers;
                quiz.QuizAnswers.setCorrectAnswer(quizVM.CorrectAnswer);

                //add quiz information
                task.TaskType = quiz.TaskType;
                task.TaskType.Quiz = quiz;

                //add taskType to task
                task.PoiID = quizVM.poiID;
                task.TaskText = quizVM.TaskText;
                task.TaskType.Image = null;
                task.TaskType.TaskTypeNum = TaskTypeNum.Quiz;
                Repo.CreateTask(task);

                return RedirectToAction("Index");
            }

            ViewBag.Message = "Task not Created";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult CreateImageTask(ImageVM imageVM, HttpPostedFileBase upload)
        {
            //initalize taskType and Task Objects
            var task = new Task();
            task.TaskType = new TaskType();

            var image = new ImageTask();

            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var file = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.CorrectImageAnswer,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        file.Content = reader.ReadBytes(upload.ContentLength);
                    }

                    image.Files = new List<File> { file };
                }

                task.TaskType.TaskTypeNum = TaskTypeNum.Image;

                //add image information
                task.TaskType.Image = image;

                //add taskType to task
                task.PoiID = imageVM.poiID;
                task.TaskText = imageVM.TaskText;
                task.TaskType.Quiz = null;
                Repo.CreateTask(task);

                return RedirectToAction("Index");
            }

            ViewBag.Message = "Task not Created";
            return RedirectToAction("Index");

        }


        public ActionResult EditTask(int id)
        {
            Task task = Repo.GetTask(id);

            if (task.TaskType.TaskTypeNum == TaskTypeNum.Image)
            {
                var imageVM = new ImageVM();
                imageVM.TaskText = task.TaskText;
                imageVM.poiID = task.PoiID;
                imageVM.Image = task.TaskType.Image;
                return View("EditImage", imageVM);
            }
            else
            {
                var quizVM = new QuizVM();
                quizVM.TaskText = task.TaskText;
                quizVM.poiID = task.PoiID;
                quizVM.QuizAnswers = task.TaskType.Quiz.QuizAnswers;
                quizVM.CorrectAnswer = task.TaskType.Quiz.QuizAnswers.CorrectAnsert;

O_ScavProtoType.UI/Controllers/POIsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using O_ScavProtoType.DAL;
using O_ScavProtoType.Model;
using O_ScavProtoType.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace O_ScavProtoType.UI.Controllers
{
    public class POIsController : Controller
    {
        private HuntContext db = new HuntContext();
        private HuntRepo repo = new HuntRepo();

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Bad need to either just get 1 hunt or go right to the poi
            var hunts = repo.GetAllHunts();

            POI poi = hunts
                .SelectMany(h => h.POIs
                .Where(p => p.Id == id))
                .SingleOrDefault();

            if (poi == null)
            {
                return HttpNotFound();
            }

            return View(poi);
        }

       public ActionResult Answer(int? taskId)
        {
            if (taskId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Task task = repo.GetTask(taskId);

            if (task == null)
            {
                return HttpNotFound();
            }

            if (task.TaskType.TaskTypeNum == TaskTypeNum.Quiz)
            {
                var quizAttempt = GetQuizAttempt(task.TaskType.Quiz);
                var answers = new List<Answer>();
                answers.Add(null);
                task.Answers = answers;

                return View("AnswerQuiz", quizAttempt);
            }

            else if(task.TaskType.TaskTypeNum == TaskTypeNum.Image)
            {
                var imageAttempt = GetImageAttempt(task.TaskType.Image);
                return View("ImageAnswer", imageAttempt);
            }
            else
            {
               //return to page with error
            }

            //return image or quiz view above
            return View(task);
        }

        [HttpPost]
        public ActionResult AnswerQuiz(QuizAttempt quizAttempt)
        {
            Task taskFromDb = repo.GetTask(quizAttempt.Quiz.TaskType.Id);

            
            string userId = User.Identity.GetUserId();

            quizAttempt.Quiz = taskFromDb.TaskType.Quiz;

            repo.CreateQuizAnswer(quizAttempt, userId);

            return RedirectToAction("Details", new { id = taskFromDb.PoiID });

        }

        //Yikes...This needs to be refactored....:/ 
        [HttpPost]
        public ActionResult AnswerImage(ImageAttempt imageAttempt, HttpPostedFileBase upload)
        {

            if (upload != null && upload.ContentLength > 0)
            {
                var file = new File
                {
                    FileName = System.IO.Path.GetFileName(upload.FileName),
                    FileType = FileType.CorrectImageAnswer,
                    ContentType = upload.ContentType
                };
                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                {
                    file.Content = reader.ReadBytes(upload.ContentLength);
                }

                imageAttempt.Image = file;
            }

            string userId = User.Identity.GetUserId();

            repo.CreateImageAttempt(imageAttempt, userId);

            return RedirectToAction("Details", new { id = 1 });
        }


        private QuizAttempt GetQuizAttempt(QuizTask quiz)
        {
            var quizAttempt = new QuizAttempt();
            quizAttempt.Quiz = quiz;
            
            return quizAttempt;
        }

        private ImageAttempt GetImageAttempt(ImageTask image)
        {
            var imageAtttempt = new ImageAttempt();
            imageAtttempt.CorrectImage = image;

            return imageAtttempt;
        }
    }
}

O_ScavProtoType.UI/Views/Hunts/Create.cshtml
@model O_ScavProtoType.UI.Models.HuntVM
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Hunt</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => Model.Hunt.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => Model.Hunt.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => Model.Hunt.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <hr />

   
    <div class="form-group">
        @Html.LabelFor(model => model.NewPoi.Name, "Point of Interest", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NewPoi.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NewPoi.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-1 col-md-5">
            <input type="submit" name ="type" value="create" class="btn btn-default btn-primary" />
        </div>
        <div class="col-md col-md-5">
            <input type="submit" name ="type" value="complete" class="btn btn-default-danger" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

O_ScavProtoType.UI/Views/Hunts/CreateImage.cshtml
@model O_ScavProtoType.UI.Models.ImageVM
@using O_ScavProtoType.Model

@{
    ViewBag.Title = "Image";
}

<h2>Image</h2>

@using (Html.BeginForm("CreateImageTask", "Hunts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.TaskText, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TaskText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TaskText, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />

        <div class="form-group">

            <div class="col-md-offset-1 col-md-5">
                @Html.Label("Correct Image")
                <input type="file" name="upload" />
            </div>
        </div>

        <div>
            @if (Model.Image.Files.Any(f => f.FileType == FileType.CorrectImageAnswer))
            {

                <img src="~/File?id=@Model.Image.Files.First(f => f.FileType == FileType.CorrectImageAnswer).FileId" alt="CorrectImage" />
            }
        </div>

        @Html.HiddenFor(image => image.poiID)
        @Html.HiddenFor(image => image.Id)
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

O_ScavProtoType.UI/Views/Hunts/CreateQuiz.cshtml
@model O_ScavProtoType.UI.Models.QuizVM

@{
    ViewBag.Title = "Quiz";
}

<h2>Task</h2>


@using (Html.BeginForm("CreateQuizTask","Hunts"))
{
   @Html.Partial("_QuizForm", Model)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Quiz.js")
    @Styles.Render("~/Content/Quiz.css") 
    <script type="text/javascript">

        $('#CorrectAnswer').change(function () {
            $('#correctAnswerValue').val($('#QuizAnswers_AnswerA').val())
        })
</script>   
}



O_ScavProtoType.UI/Views/Hunts/Delete.cshtml
@model O_ScavProtoType.Model.Hunt

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hunt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed","Hunts")) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.HiddenFor(model => model.Id)
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

O_ScavProtoType.UI/Views/Hunts/DeleteTask.cshtml
@model O_ScavProtoType.Model.Task

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Task</h4>
    <hr />
    <dl class="dl-horizontal">
        @Html.LabelFor(m => m.TaskText)
        <dd>
            @Html.DisplayFor(model => model.TaskText)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteTaskConfirmed", "Hunts")) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

O_ScavProtoType.UI/Views/Hunts/Details.cshtml
@model O_ScavProtoType.Model.Hunt



<h2>@Model.Name</h2>

<div>
    <h4>Hunt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Places of Interest
        </dt>
        @foreach (var mod in @Model.POIs)
        {
            <dd>
                <span>@mod.Name</span> <span>@Html.ActionLink("Tasks", "Details", "POIs", new { id = mod.Id }, null )</span>
            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

O_ScavProtoType.UI/Views/Hunts/Edit.cshtml
@model O_ScavProtoType.UI.Models.HuntVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Hunt</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Hunt.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Hunt.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hunt.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hunt.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <h4>POI's</h4>

        <div class="col-md-5">

            <dl>
                @*<dt>
                    Places of Interest
                </dt>*@

                @for (var i = 0; i < Model.pois.Count(); i++)
                {
                    <dd>
                       <span>@Model.pois[i].Name</span>
                        <span class="pull-right">@Html.ActionLink("Edit POI", "EditPOI",new { poiID = Model.pois[i].Id })</span>
                    </dd>
                }
            </dl>

        </div>

        <div class="form-group">
            <div class="col-md-5">
                @Html.EditorFor(model => model.NewPoi.Name, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.NewPoi.Name, "", new { @class = "text-danger" })
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>


    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

O_ScavProtoType.UI/Views/Hunts/EditImage.cshtml
@model O_ScavProtoType.UI.Models.ImageVM
@using O_ScavProtoType.Model

@{
    ViewBag.Title = "Image";
}

<h2>Image</h2>

@using (Html.BeginForm("EditImageTask", "Hunts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
 @Html.Partial("_ImageForm",Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

O_ScavProtoType.UI/Views/Hunts/EditQuiz.cshtml
@model O_ScavProtoType.UI.Models.QuizVM

@{
    ViewBag.Title = "Quiz";
}

<h2>Task</h2>


@using (Html.BeginForm("EditQuizTask", "Hunts"))
{

    @Html.Partial("_QuizForm", Model)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Quiz.js")
    @Styles.Render("~/Content/Quiz.css")
}



O_ScavProtoType.UI/Views/Hunts/Index.cshtml
@model IEnumerable<O_ScavProtoType.Model.Hunt>


<h2>Hunts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

O_ScavProtoType.UI/Views/Hunts/Manage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" id="huntArea">
    <div class="col-md-6">
        <button type="button" class="btn-lg btn-primary" id="createHuntButton">@Html.ActionLink("Create Hunt", "Create", "Hunts")</button>
    </div>
    <div class="col-md-6">
        <button type="button" class="btn-lg btn-warning">@Html.ActionLink("Play Hunt", "Index", "Hunts")</button>
    </div>
</div>

O_ScavProtoType.UI/Views/Hunts/Poi.cshtml
@using O_ScavProtoType.Model
@model O_ScavProtoType.UI.Models.PoiVM


<h2>Edit</h2>

@using (Html.BeginForm("EditPOI", "Hunts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{ @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>POI</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Poi.Id)
        @Html.HiddenFor(model => model.Poi.HuntID)
        <div class="form-group">
            @Html.LabelFor(model => model.Poi.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poi.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poi.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poi.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Poi.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poi.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-offset-1 col-md-5">
                @Html.Label("Image")
                <input type="file" id="PoiImage" name="upload" />
            </div>
        </div>
        <div>
            @if (Model.Poi.Files.Any(f => f.FileType == FileType.PoiImage))
            {

                <img src="~/File?id=@Model.Poi.Files.First(f => f.FileType == FileType.PoiImage).FileId" alt="POIImage" />
            }
        </div>
        <br />
        <input type="submit" value="Save POI" class="btn btn-default" />


    </div>
}

<hr />

<div>
    <h4>Tasks</h4>

    <div class="col-md-6">

        <div class="bs-example" data-example-id="striped-table">
            <table class="table table-striped">
                <tbody>
                    @for (var i = 0; i < Model.Task.Count(); i++)
            {

                        <tr>
                            <td>@Model.Task[i].TaskText</td>
                            <td>@Html.ActionLink("Edit", "EditTask", new { id = Model.Task[i].Id })</td>
                            <td>@Html.ActionLink("Delete", "DeleteTask", new { id = Model.Task[i].Id })</td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>



    </div>



    <h4>New Task</h4>
    <div class="col-md-6">
        @Html.Label("Task Name")

        @using (@Html.BeginForm("CreateTasks", "Hunts", FormMethod.Get))
        {
            @Html.EditorFor(model => model.NewTask.TaskText, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NewTask.TaskText, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.Label(TaskTypeNum.Image.ToString(), new { @class = "radio-inline" })
                @Html.RadioButtonFor(m => m.taskType, TaskTypeNum.Image)

                @Html.Label(TaskTypeNum.Quiz.ToString(), new { @class = "radio-inline" })
                @Html.RadioButtonFor(m => m.taskType, TaskTypeNum.Quiz)
            </div>

            @Html.HiddenFor(m => m.Poi.Id)
            <input type="submit" value="Create Task" class="btn btn-default" />
        }

        <br />
    </div>

    @Html.ActionLink("Back to List", "Index")


</div>

O_ScavProtoType.UI/Views/Hunts/_ImageForm.cshtml
@model O_ScavProtoType.UI.Models.ImageVM
@using O_ScavProtoType.Model

@Html.AntiForgeryToken()

<div class="form-group">
    @Html.LabelFor(model => model.TaskText, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.TaskText, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TaskText, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-horizontal">
    <h4>Image</h4>
    <hr />

    <div class="form-group">

        <div class="col-md-offset-1 col-md-5">
            @Html.Label("Correct Image")
            <input type="file" name="upload" />
        </div>
    </div>

    <div>
        @if (Model.Image.Files.Any(f => f.FileType == FileType.CorrectImageAnswer))
            {

            <img src="~/File?id=@Model.Image.Files.First(f => f.FileType == FileType.CorrectImageAnswer).FileId" alt="CorrectImage" />
        }
    </div>

    @Html.HiddenFor(image => image.poiID)
    @Html.HiddenFor(image => image.Id)
</div>